### ISSUE TITLE
Mock UI - Notification icon 

### ISSUE THREAD

**Issue by karalabe** [coronanet/rn-coronanet#6]
Since we need to constantly show a notification for our foreground service on Android, we kind of need an icon for it. This is shown both on the notification itself, as well as on the notification bar:

![Screenshot_20200319-201717_One UI Home](https://user-images.githubusercontent.com/129561/77100812-eadaea80-6a1e-11ea-8f7b-2ec44d59ef4e.jpg)

![Screenshot_20200320-152421_One UI Home](https://user-images.githubusercontent.com/129561/77167653-1b726100-6abf-11ea-9814-09355df17342.jpg)

We kind of need something nicer instead of the stock green Android. If someone could help us design something simple that feels in place, I'd be grateful. Something looking like a corona virus, just one that's actually recognizable at such a low resolution.

Something like http://clipart-library.com/2020/imgbin-computer-icons-coronavirus-computer-font-font-corona-BnK9AU9cRZufp4mZJ3VRgPceZ.jpg maybe.

**Comment by daodesigner** [comment]
![covid24*24](https://user-images.githubusercontent.com/58278045/77215520-de23c880-6aea-11ea-8302-b73f378cfd29.png)
![covid36*36](https://user-images.githubusercontent.com/58278045/77215522-de23c880-6aea-11ea-9126-cd2ad3edc2fc.png)
![covid48*48](https://user-images.githubusercontent.com/58278045/77215523-debc5f00-6aea-11ea-8e4d-391cb688c9fa.png)
![covid72*72](https://user-images.githubusercontent.com/58278045/77215524-debc5f00-6aea-11ea-97dd-b4de283620af.png)
![covid96*96](https://user-images.githubusercontent.com/58278045/77215525-debc5f00-6aea-11ea-976f-4b4215498cbb.png)
![covid250*250](https://user-images.githubusercontent.com/58278045/77215526-debc5f00-6aea-11ea-986d-50104c0ad0e5.png)
